camel:
  springboot:
    main-run-controller: true


spring:
  artemis:
    mode: native
    broker-url: "tcp://localhost:61616"
    user: "artemis"
    password: "artemis"


simulator:
  dataGeneratorInputEndpoint: "timer:MOCK_DATA?period=5s"
  inputEndpoint: "direct:sendToAuditQueue"
  outputEndpoint: "jms:queue:EmailAuditQueue?jmsMessageType=object"

