camel:
  springboot:
    main-run-controller: true


spring:
#  docker:
#    compose:
#      enabled: true
#      file: "compose.yaml"
  artemis:
    mode: native
    broker-url: "tcp://localhost:61616"
    user: "artemis"
    password: "artemis"


inputEndpoint: "jms:queue:EmailAuditQueue"

