camel:
  springboot:
    main-run-controller: true

spring:
  artemis:
    mode: native
    broker-url: "tcp://localhost:61616"
    user: "artemis"
    password: "artemis"
  datasource:
    url: "jdbc:h2:file:/tmp/email_audit/db"
  jpa:
    hibernate:
      ddl-auto: update


inputEndpoint: "jms:queue:EmailAuditQueue"

